### ISSUE TITLE
Error: permission denied

### ISSUE THREAD

**Issue by dentaku65** [wheelybird/openvpn-server-ldap-otp#11]
Hi,

when I run the container the container does not create anything.

This is my command

> docker run \
>            --name openvpn \
>            --volume /home/user/OPENVPN:/etc/openvpn \
>            --detach=true \
>            -p 1194:1194/udp \
>            -e "OVPN_SERVER_CN=my.xxx.host" \
>            -e "LDAP_URI=server.xxx.dom" \
>            -e "LDAP_BASE_DN=OU=VPN,OU=Other_Users,DC=yyy,DC=dom" \
>            -e "LDAP_BIND_USER_DN=dom\user" \
>            -e "LDAP_BIND_USER_PASS=xxxxx" \
>            -e "OVPN_NETWORK=10.239.239.0 255.255.255.0" \
>            -e "OVPN_ROUTES=192.168.0.0 255.255.0.0" \
>            -e "OVPN_DNS_SERVERS=192.168.0.205,192.168.0.212" \
>            -e "OVPN_DNS_SEARCH_DOMAIN=yyy.dom" \
>            -e "OVPN_REGISTER_DNS=true" \
>            --cap-add=NET_ADMIN \
>            wheelybird/openvpn-ldap-otp

Seems that the image load correctly, but if I execute:

> docker logs openvpn

I see:

> mkdir: cannot create directory `/etc/openvpn/logs': Permission denied

Can you please give me some hints?
Thanks in advance.
Den

**Comment by wheelybird** [comment]
Hello.

As you've bind-mounted a local directory into the container you'll need to check the permissions on that local directory (`/home/user/OPENVPN`).  The container will try and create the `logs` directory in there, but it can only do that if the user that Docker runs as has permissions to write to that directory.

**Comment by dentaku65** [comment]
Hello wheelybird,
I confirm that the user has full permissions on the directory; but the log say a different path. Strange thing, starting docker run with sudo (I don't needed on my box since that my user is in the docker group) I got another error:

> mknod: `/dev/net/tun': Operation not permitted

br,
den

**Comment by wheelybird** [comment]
Which operating system/distribution are you using?  Could you run `ls -la /home/user/OPENVPN`?

**Comment by dentaku65** [comment]
"user" was an example... anyway

> neulift@nllin01:~/OPENVPN$ pwd
> /home/neulift/OPENVPN
> neulift@nllin01:~/OPENVPN$ ls -al
> total 8
> drwxrwxr-x  2 neulift neulift 4096 Mar 15 13:46 .
> drwxr-xr-x 10 neulift neulift 4096 Mar 15 13:46 ..
> neulift@nllin01:~/OPENVPN$ cat /etc/lsb-release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
> neulift@nllin01:~/OPENVPN$

**Comment by wheelybird** [comment]
I'm unable to recreate either error on another Ubuntu 18.04 installation.  For the bind-mount directory try specifying a directory that doesn't yet exist; Docker will create the directory itself with the required permissions.
I don't know why you're getting `mknod: `/dev/net/tun': Operation not permitted` when running via sudo.  Using sudo shouldn't make any difference as it's simply passing the instructions to the Docker daemon, and it's the daemon that runs the container.
Do you have another Ubuntu instance you can try running this from?

**Comment by wheelybird** [comment]
Jolly good.  Glad it all got sorted. :D
