### ISSUE TITLE
Fatal - iptables

### ISSUE THREAD

**Issue by Jayrgo** [wheelybird/openvpn-server-ldap-otp#15]
Hi,

i created a container on Synology with minimal configuration (OVPN_PROTOCOL, LDAP_BASE_DN, LDAP_URI, OVPN_SERVER_CN) and get this error on latest build.
```
iptables: masquerade from 10.50.50.0/24 to everywhere via eth0
FATAL: Could not load /lib/modules/4.4.59+/modules.dep: No such file or directory
iptables v1.4.7: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
FATAL: Could not load /lib/modules/4.4.59+/modules.dep: No such file or directory
iptables v1.4.7: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

**Comment by wheelybird** [comment]
Hi.
This sounds very much like an issue with the kernel & kernel modules provided by Synology. Could I suggest that you raise the issue with Synology support?  They're probably well aware of the issue and can offer a workaround.
