### ISSUE TITLE
Management interface support

### ISSUE THREAD

**Issue by StarGate01** [wheelybird/openvpn-server-ldap-otp#16]
Hi,

the OpenVPN server may be configured to expose a TCP status and management service on a secondary port. (See https://openvpn.net/community-resources/management-interface/)

This functionality is needed for administration tools like web-based status monitors etc. (See http://openvpn-monitor.openbytes.ie/ or https://github.com/adamwalach/openvpn-web-ui for example)

**I propose the following changes:**
 - Add a setting variable to optionally enable the management interface (disabled by default)
 - Add setting variables to configure the binding address and authentification (see below)
 - Use the TCP port `5555`

**Security considerations:**
 - The interface should be protected by a password, which shall be supplied using another setting variable. However, in a closed system where no outside access is possible, a password may not be needed. There also may be tools which do not support authentification. Disabled by default.
 - The interface should be bound on `127.0.0.1` only to prevent outside access (recommended by OpenVPN), however this breaks certain configurations - e.g. docker-compose networking. Therefore, this should be user configurable (see above). The user should be warned to implement sufficient security measures to protect the management interface from the outside internet, e.g. by using docker-compose's "`expose`" and "`port`" directives. `127.0.0.1` by default.

**Implementation:**
- `EXPOSE` another port (`5555`). This should not be user configurable, as it may be routed by docker or the user to a different port, and a static port simplifies development for us.
- Add the management (See https://openvpn.net/community-resources/reference-manual-for-openvpn-2-0/ and https://openvpn.net/community-resources/management-interface/) directive to the server configuration file generator.
- If needed, store the authentification password in a password file as required by the directive. Protect this file.

**Discussion:**
 - Are the defaults sane?
 - Are there better alternatives to storing the password in a password file?
 - I recommend a mechanism to only start the interface on a binding address dissimilar to localhost when a password is set. Is this really needed?

Is this is a helpful change, I will continue working on a pull request concering this issue.

**Comment by wheelybird** [comment]
Hi.
Thanks for the suggestion.  I can't see any issue with this request.  

With regards to binding to 127.0.0.1, that would only be available from _inside_ the container and therefore doesn't make any sense to do that.   It doesn't really matter which port we set for the management interface as people will map the host port they want to use to the container port.  So 5555 is as good as any.
The documentation suggests that you can either set the password via the file or via STDIN (interactively at startup).  As we can't have an interactive startup then setting it by file is the only other option.  I also think it would be better to require a password to be set unless another variable like *DEFINITELY_NO_MANAGEMENT_PASSWORD_PLEASE* is set to true, just to ensure nobody unintentionally configures their VPN with easy access to the management interface.

Let me know if this is something you want to work on, otherwise I'll add it.  It'll be a couple of weeks at least before I have the spare time for it though.

**Comment by StarGate01** [comment]
Hi,
thank you for your feedback.

>  binding to 127.0.0.1

Yes, on my server I bound it to 0.0.0.0. Because we run in a containerized system, should we leave out the host IP setting completely?

> setting it by file

Thats what I thought, however I don't think thats too much of a security issue.

> DEFINITELY_NO_MANAGEMENT_PASSWORD_PLEASE
> ensure nobody unintentionally configures their VPN with easy access to the management interface.

This is a great idea, I would imagine the new configuration options to look something like this:
 - `OVPN_MANAGEMENT_ENABLE `(false)
 - `OVPN_MANAGEMENT_PASSWORD `()
 - `OVPN_MANAGEMENT_NOAUTH `(false)

And the program flow like this:
```
if OVPN_MANAGEMENT_ENABLE then
    if OVPN_MANAGEMENT_NOAUTH then
        if OVPN_MANAGEMENT_PASSWORD is set then warn the user that no auth will be used
        enable management interface without password
    else
        if OVPN_MANAGEMENT_PASSWORD is set then
            enable management interface with password
        else
            warn the user that a password or the noauth option is required
        end if
    end if
end if
```

> Let me know if this is something you want to work on

I already am running a forked version of this repo on my server where I roughly patched in the management support. I would just clean up the code and create a pull request here in the near future (the next days or weeks).

**Comment by wheelybird** [comment]
That all looks good.  Binding to 0.0.0.0 will work fine.

**Comment by wheelybird** [comment]
That's merged in now.  Cheers for the PR.
