### ISSUE TITLE
LDAPS self-signed certificate

### ISSUE THREAD

**Issue by CarlesLlobet** [wheelybird/openvpn-server-ldap-otp#19]
Hi,

I am using a self-signed certificate but I am unable to connect through LDAPS.
I explain the scenario:

- I have a working configuration with LDAP with a docker-compose
- I add the `LDAP_TLS`=true environment variable to the docker-compose
- I change the prefix in de `LDAP_URI` variable from _ldap://myldap.com_ to _ldaps://myldap.com_
- I add the `LDAP_TLS_CA_CERT` variable with my self-signed certificate

And the connection does not work. I am pretty sure I am not configuring properly the `LDAP_TLS_CA_CERT` variable. First I mounted an extra binded volume to share the certificate, and I added the certificate containers path to the variable. But later I realized in your `LDAP_TLS_CA_CERT` description that you say _"**The contents** of the CA certificate file for the LDAP server"_. So I have tried to copy all the certificate without breaklines, but still does not work.

How is this variable supposed to work? Could you improve the description?

Thanks in advance!

**Comment by wheelybird** [comment]
Hi.  Yes, this can probably be explained better.   The LDAP_TLS_CA_CERT is for the Certificate Authority certificate.  You might use this if you created self-signed certificates for LDAP by using your own Certificate Authority and so the CA certificate won't be in the preinstalled list of CA certificates.
If you're using a self-signed certificate in LDAP and you _didn't_ create them with your own CA then you can set `LDAP_TLS_VALIDATE_CERT` to `false` and that way the LDAP client will ignore the missing CA certificate.  Let me know if that's clearer.

**Comment by CarlesLlobet** [comment]
> Hi. Yes, this can probably be explained better. The LDAP_TLS_CA_CERT is for the Certificate Authority certificate. You might use this if you created self-signed certificates for LDAP by using your own Certificate Authority and so the CA certificate won't be in the preinstalled list of CA certificates.
> If you're using a self-signed certificate in LDAP and you _didn't_ create them with your own CA then you can set `LDAP_TLS_VALIDATE_CERT` to `false` and that way the LDAP client will ignore the missing CA certificate. Let me know if that's clearer.

Hi @wheelybird, thanks for the quick respone.
I did create the LDAP certificates with my own CA, so I need to pass it to LDAP_TLS_CA_CERT. 
I've seen in the [ldap script](https://github.com/wheelybird/openvpn-server-ldap-otp/blob/master/files/configuration/setup_ldap.sh) in line 27 that you echo the variable directly to a file.
The problem is that docker-compose is a YAML file, and YAML is so cumbersome and annoying with identations and spaces. I have been trying for a while in different formats, but the certificate in the end file (ldap-ca.crt) is not idented as it should be.

Could you provide a working example with a yaml file with LDAP_TLS_CA_CERT with the certificate copyied there?

Even better, wouldn't it be more easy to just provide a path pointing to the CA__CERT in this variable? I see to options here. A path to the host where the certificate is, and doing a docker cp once the container is up (not really sure if it'd work), or sharing a volume for the CA_CERT and just giving the container path where the cert should be found.

**Comment by wheelybird** [comment]
You should be able to use a YAML scalar for the certificate (https://yaml.org/spec/spec.html#id2561378).
For example,

```
...
...
  environment:
    - LDAP_TLS_CA_CERT: |
         -----BEGIN CERTIFICATE-----
         MIIDBzCCAe+gAwIBAgIJALOT/fiqj4yhMA0GCSqGSIb3DQEBBQUAMBoxGDAWBgNV
         BAMMD3d3dy5leGFtcGxlLmNvbTAeFw0xNzA1MDMxNDA2NDVaFw0yNzA1MDExNDA2
         NDVaMBoxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEB
         BQADggEPADCCAQoCggEBALHEIGNhuQsD1MI3zE5Kts5zN91ggbFjFq0aLWjYuIB6
         ttfpS158b9x9oWbdACAqGIHC5i1/iwiJkW8J1UcxtPOOHZy4s9E48KnPzJOd6yAv
         BQADggEPADCCAQoCggEBALHEIGNhuQsD1MI3zE5Kts5zN91ggbFjFq0aLWjYuIB6
         TXSC5iLK1XPCd6aQpDZwxQpjDNeDk9CR6asqtPJcm9X2skLuNWyIr8dKHpdzoQ5A
         /5GhmtLC/WYwZdqi14Gwph+GS7a2eQYzbGwIZWfcPiMytoNGidDC2HurRpGt91PK
         PxfXDhDk8taBuboHFDAW7beR/x68pPm+p2mTtVt+cS0CAwEAAaNQME4wHQYDVR0O
         BQADggEPADCCAQoCggEBALHEIGNhuQsD1MI3zE5Kts5zN91ggbFjFq0aLWjYuIB6
         By/QRQI8PipqMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAFh6UUfa
         YL9iLREMGgHTvn4O4nMtsWEEW46/9o4ZcGgVgIL343qD1G0isaTLStKHB5C653N0
         40DU/n9Fcver/x5EhKzjp9QcOSNizFDUG88tCOuW3H+EsTHsCwxdVvENzBT1+Z3N
         JkT8oHVjEc3LBeQmVZLHiWWA9CSVW9b6qco0OjLwLe92f1EWKjqrHPW+5xM3zC0e
         T2h5p4ApY74Pyl892HJrb/dd2DjzYDnXuvcDFZTAr9o5YgcS1jx0Gt9jE1FM7rhk
         GF5aek4Bir9K8xwNBTc8R+dvl2OhQYoxIglSApkNI+n0J9/1pfPnpwojBHifqy/p
         G9oErrv2EQ642e4=
         -----END CERTIFICATE-----
    - LDAP_URI: ldaps://yourldapserver.io
...
...
```

**Comment by CarlesLlobet** [comment]
This is one of the tests I did yesterday, as you can see in this obfuscated screenshot:
![image](https://user-images.githubusercontent.com/6575422/59017342-9d044580-8843-11e9-9630-9f6b8052e6dd.png)

Once I connect, the logs say the following:

`AUTH-PAM: BACKGROUND: user 'xxxxxxx' failed to authenticate: Authentication service cannot retrieve authentication info
Thu Jun  6 08:11:28 2019 192.168.XX.XX:54800 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so/PLUGIN_AUTH_USER_PASS_VERIFY status=1
Thu Jun  6 08:11:28 2019 192.168.XX.XX:54800 PLUGIN_CALL: plugin function PLUGIN_AUTH_USER_PASS_VERIFY failed with status 1: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
Thu Jun  6 08:11:28 2019 192.168.XX.XX:54800 TLS Auth Error: Auth Username/Password verification failed for peer
Thu Jun  6 08:11:28 2019 192.168.XX.XX:54800 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA
Thu Jun  6 08:11:28 2019 192.168.XX.XX:54800 Peer Connection Initiated with [AF_INET]192.168.XX.XX:54800
Thu Jun  6 08:11:29 2019 192.168.XX.XX:54800 PUSH: Received control message: 'PUSH_REQUEST'
Thu Jun  6 08:11:29 2019 192.168.XX.XX:54800 Delayed exit in 5 seconds
Thu Jun  6 08:11:29 2019 192.168.XX.XX:54800 SENT CONTROL [UNDEF]: 'AUTH_FAILED' (status=1)
Thu Jun  6 08:11:34 2019 192.168.XX.XX:54800 SIGTERM[soft,delayed-exit] received, client-instance exiting`

And if I cat the imported CA, it looks like this:
![image](https://user-images.githubusercontent.com/6575422/59017552-10a65280-8844-11e9-9bc7-ba5ea33e15e8.png)

I guess the Authentication failing for peer it is due the bad identation of the ldap-ca.crt certificate imported. It even has the scalar sign in it..

**Comment by wheelybird** [comment]
Hi.  To be frank, this is really an issue with Docker compose and YAML formatting rather than this container.
However,  I've tested this compose file structure and it passes a properly formatted CA certificate into the container:
```
version: '3'

services:
  openvpn:
    image: wheelybird/openvpn-ldap-otp:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - /opt/docker/openvpn:/etc/openvpn
    environment:
      OVPN_SERVER_CN: example.vpn.io
      LDAP_BASE_DN: example.io
      LDAP_TLS: "true"
      LDAP_URI: ldaps://yourldapserver.io
      LDAP_TLS_CA_CERT: |
         -----BEGIN CERTIFICATE-----
         MIIDBzCCAe+gAwIBAgIJALOT/fiqj4yhMA0GCSqGSIb3DQEBBQUAMBoxGDAWBgNV
         BAMMD3d3dy5leGFtcGxlLmNvbTAeFw0xNzA1MDMxNDA2NDVaFw0yNzA1MDExNDA2
         NDVaMBoxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEB
         BQADggEPADCCAQoCggEBALHEIGNhuQsD1MI3zE5Kts5zN91ggbFjFq0aLWjYuIB6
         ttfpS158b9x9oWbdACAqGIHC5i1/iwiJkW8J1UcxtPOOHZy4s9E48KnPzJOd6yAv
         BQADggEPADCCAQoCggEBALHEIGNhuQsD1MI3zE5Kts5zN91ggbFjFq0aLWjYuIB6
         TXSC5iLK1XPCd6aQpDZwxQpjDNeDk9CR6asqtPJcm9X2skLuNWyIr8dKHpdzoQ5A
         /5GhmtLC/WYwZdqi14Gwph+GS7a2eQYzbGwIZWfcPiMytoNGidDC2HurRpGt91PK
         PxfXDhDk8taBuboHFDAW7beR/x68pPm+p2mTtVt+cS0CAwEAAaNQME4wHQYDVR0O
         BQADggEPADCCAQoCggEBALHEIGNhuQsD1MI3zE5Kts5zN91ggbFjFq0aLWjYuIB6
         By/QRQI8PipqMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAFh6UUfa
         YL9iLREMGgHTvn4O4nMtsWEEW46/9o4ZcGgVgIL343qD1G0isaTLStKHB5C653N0
         40DU/n9Fcver/x5EhKzjp9QcOSNizFDUG88tCOuW3H+EsTHsCwxdVvENzBT1+Z3N
         JkT8oHVjEc3LBeQmVZLHiWWA9CSVW9b6qco0OjLwLe92f1EWKjqrHPW+5xM3zC0e
         T2h5p4ApY74Pyl892HJrb/dd2DjzYDnXuvcDFZTAr9o5YgcS1jx0Gt9jE1FM7rhk
         GF5aek4Bir9K8xwNBTc8R+dvl2OhQYoxIglSApkNI+n0J9/1pfPnpwojBHifqy/p
         G9oErrv2EQ642e4=
         -----END CERTIFICATE----
```
Note that I'm using colons rather than equal signs and *true* needs to be quoted.

That should get you up and running.

**Comment by CarlesLlobet** [comment]
Hi @wheelybird!

Thanks! **I changed the docker format from having enviroment vars with hyphens at the beggining and equal sings to colons, and it did copy the certificate properly idented**.

I guess it must be some kind of docker problem with env var definitions.

I will delete the last comment to avoid confidentiality issues, although it was already obfuscated.

**Comment by wheelybird** [comment]
For all its simplicity, YAML can be frustratingly difficult sometimes. :)  Glad you got it sorted.

**Comment by CarlesLlobet** [comment]
Hi @wheelybird,

I know this issue has been closed but it is so related to it that I think it is better to continue inside this thread.

As I told you, I the ldap-ca.crt file now is a properly idented file with my own CA cert there.
But LDAP doesn't connect properly. I have been debugging it.

If I enter inside the continer (docker exec -it container_name bash) and execute a normal ldapsearch (to do so you'll have to install ldapsearch first (yum install openldap-clients), it works as a charm.
Concretely, the ldapsearch command I execute is:

![image](https://user-images.githubusercontent.com/6575422/59275758-3d4fd500-8c5d-11e9-8ff4-d8c716df65fe.png)

I specify (respectively) the hostname, the user to execute the search and his password (no anonymous search allowed), and the BaseDN. Lastly, the LDAP_LOGIN_ATTRIBUTE because I am working with an Active Directory is set to sAMAccountName.

If I execute the command like this, it works perfectly, but if I put the last parameter "-Z" wich enables TLS, it responds with the following message:

![image](https://user-images.githubusercontent.com/6575422/59275953-a5062000-8c5d-11e9-822b-21c76e843f12.png)

I have tried installing the CA certificate manually following this:
![image](https://user-images.githubusercontent.com/6575422/59276001-be0ed100-8c5d-11e9-9b58-7597cadd907b.png)

But still the same result.

On my host (outside the container) I can execute both with and without the Z flag (with and without TLS), but inside the container just works without TLS. And on my host I just had to install the certificate with "update-ca-certificates" and it worked.

What can be happening? I have tried so many things and to simplify the error as much as I can. But this ldapsearch behaviour inside/outside the container is killing me. Couldn't be more simple. I don't know why inside the container it is not working. 

**Maybe the certificate is not installing properly although it is getting it correctly from the docker-compose? 

If that's the case, why? And shouldn't it be working once I install it manually? Maybe I should install the certificate manually in another way?**

Sorry for the inconvenience. I hope at least this is useful to you by finding a bug in a certain scenario.

Thanks in advance,

**Comment by CarlesLlobet** [comment]
I have been searching a lot about this specific error message with ldap on centOS, and all seems to be about the Key Usage definition on the certificate, as the error states:
`TLS error -8102:Certificate key usage inadequate for attempted operation.`

Here there's an example (https://groups.google.com/forum/#!topic/vault-tool/keXvvOzf6x4), but they do not explicit what specific extensions should the certificate have.

Running ` openssl x509 -in certs/rootsrvdc001.cer -text` i can see the following extensions in my certificate:

![image](https://user-images.githubusercontent.com/6575422/59281918-5e69f300-8c68-11e9-9327-8137d6efdfc6.png)


As you can see, Key Usage is defined with "Digital Signature, Certificate Sign and CRL Sign". Am I missing any other Key Usage extension?

**Comment by wheelybird** [comment]
Hi.  You should probably have `extendedKeyUsage = serverAuth` set.

Try this script:
```
#!/bin/bash

domain_suffix="yourdomain.io"
hostnames="ldap ldap-a ldap-b"

if [ ! -f "ca.key" ]; then
  echo "Generating CA key..."
  openssl genrsa -out ca.key 2048
fi

if [ ! -f "ca.crt" ]; then
  echo "Generating CA cert..."
  openssl req \
    -new \
    -x509 \
    -key ca.key \
    -nodes \
    -days 7300 \
    -subj '/CN=LDAPCA/O=YOU/C=GB' \
    -out ca.crt
fi

if [ ! -f "server.key" ] || [ ! -f "server.crt" ]; then

  echo "Generating certificate config..."
  for this_hostname in $hostnames; do san_list="${this_hostname}.${domain_suffix} $san_list"; done
  shopt -s extglob
  san_list=${san_list%% }
  san_list="DNS:${san_list//+([[:blank:]])/,DNS:}"
  echo "subjectAltName = $san_list,IP:127.0.0.1" > server.cnf
  echo "extendedKeyUsage = serverAuth" >> server.cnf

  echo "Generating server key..."
  openssl genrsa -out server.key 2048

  echo "Generating server CSR..."
  openssl req -subj "/CN=ldap" -sha256 -new -key server.key -out server.csr

  echo "Generating server cert..."
  openssl x509 -req -days 7300 -sha256 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -extfile server.cnf

  rm server.csr
  rm server.cnf

fi
```
