### ISSUE TITLE
How to use this permanently

### ISSUE THREAD

**Issue by jdkruzr** [wheelybird/openvpn-server-ldap-otp#2]
Hi,

This is less of an "issue" and more of a question -- so, that docker run command sets everything up, right? What is the Right Way to start that container at boot? Does it "start over" every time or is there some kind of persistent state that it uses? (I feel like there would have to be a persistent state so that your OTP data stays the same between server reboots?)

Thanks.

**Comment by wheelybird** [comment]
When you bind-mount a local directory (`--volume /path/on/host:/etc/openvpn`) the config files will be persistent on the host between restarts.
You can also add `--restart=always` to your `docker run` command to ensure it starts up again on failure or if the host reboots.
