### ISSUE TITLE
Allow LDAP over SSL not only StartTLS

### ISSUE THREAD

**Issue by agherzan** [wheelybird/openvpn-server-ldap-otp#29]
https://github.com/wheelybird/openvpn-server-ldap-otp/blob/dfc1412c30a5f089781ebea67f6a2e8f899ba672/files/configuration/setup_ldap.sh#L20

The current LDAP configuration forces `ssl` to StartTLS but that might not be appropriate for all deployments. Allow `ssl on` as well.

**Comment by wheelybird** [comment]
I've added this option in the v1.2 release.  You can set `LDAP_ENCRYPT_CONNECTION` to `on`, which will set nslcd.conf to `ssl on`.

**Comment by agherzan** [comment]
Thanks. This works great now.
