### ISSUE TITLE
Split bash variable by comma in configuration scripts

### ISSUE THREAD

**Issue by mshockwave** [wheelybird/openvpn-server-ldap-otp#3]
Some environment variables are consist of comma-separated list. And configuration scripts would use `FS=','` along with `read` to get individual elements. For example, [configuration/create_server_config.sh](https://github.com/wheelybird/openvpn-server-ldap-otp/blob/master/files/configuration/create_server_config.sh#L23)

However, I found that it didn't work as expected, list of values remain unsplit. The following way works for me though:
```
IFS=',' read -r -a output_list <<< $COMMA_SEPARATED_ENV_VAR
for e in ${output_list[@]}; do
  (loop body...)
done
```
I would send a PR later.

**Comment by wheelybird** [comment]
This should be fixed now.
