### ISSUE TITLE
OVPN_MANAGEMENT_ENABLE=true 

### ISSUE THREAD

**Issue by atila01380** [wheelybird/openvpn-server-ldap-otp#32]
Hi,

I would like to  use https://github.com/ruimarinho/docker-openvpn-monitor container to monitor openvpn-server-ldap-otp.

So i add  `OVPN_MANAGEMENT_ENABLE=true` in  environement variable

But i don't see `management 0.0.0.0 5555 ` line in the server.conf ?

And in second is  it necesary  to put 5555:5555 in  the docker command ?

Thanks for your great job.

Bertrand

**Comment by wheelybird** [comment]
Hi.  Do you also have OVPN_MANAGEMENT_PASSWORD set?  If OVPN_MANAGEMENT_NOAUTH is set to false (the default) then management won't be enabled. You should see a message in the startup logs saying that.
With regards to exposing the port, you could do that or alternatively you could create a Docker network and attach both containers to that network.  Then your monitoring container would be able to connect to the OpenVPN container by its name on port 5555 without the need to publicly expose it.  More information on setting up Docker networks can be found here:  https://docs.docker.com/network/network-tutorial-standalone/

**Comment by atila01380** [comment]
Hi,
Nice thanks for your answer it's works fine :)
