### ISSUE TITLE
load openldap faild

### ISSUE THREAD

**Issue by AEGEGE** [wheelybird/openvpn-server-ldap-otp#34]
Hello!
When I used this image to connect to openldap, there was a problem. I kept saying that the authentication failed. I tried many methods. The following is the startup file and the error is reported.

`docker run \
           --name openvpn \
           --detach=true \
           -p 1194:1194/tcp \
           -e OVPN_PROTOCOL="tcp" \
           -e OVPN_NAT="false" \
           -e OVPN_SERVER_CN="openvpn.xxx.com" \
           -e OVPN_ROUTES="192.168.216.0 255.255.255.0" \
           -e LDAP_URI="ldap://192.168.157.129" \
           -e LDAP_BASE_DN="dc=xxx,dc=com" \
           --cap-add=NET_ADMIN \
           -e LDAP_BIND_USER_DN="cn=admin,dc=xxx,dc=com" \
           -e LDAP_BIND_USER_PASS="123456" \
           -v /etc/localtime:/etc/localtime:ro \
           -v /data/openvpn:/etc/openvpn \
           wheelybird/openvpn-ldap-otp:v1.2`

Sat May 16 17:10:13 2020 192.168.157.1:62978 peer info: IV_GUI_VER="net.tunnelblick.tunnelblick_5440_3.8.2beta04__build_5440)"
AUTH-PAM: BACKGROUND: user 'xingzheng' failed to authenticate: User not known to the underlying authentication module
Sat May 16 17:10:13 2020 192.168.157.1:62978 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so/PLUGIN_AUTH_USER_PASS_VERIFY status=1
Sat May 16 17:10:13 2020 192.168.157.1:62978 PLUGIN_CALL: plugin function PLUGIN_AUTH_USER_PASS_VERIFY failed with status 1: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
Sat May 16 17:10:13 2020 192.168.157.1:62978 TLS Auth Error: Auth Username/Password verification failed for peer
Sat May 16 17:10:13 2020 192.168.157.1:62978 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA
Sat May 16 17:10:13 2020 192.168.157.1:62978 Peer Connection Initiated with [AF_INET]192.168.157.1:62978
Sat May 16 17:10:15 2020 192.168.157.1:62978 PUSH: Received control message: 'PUSH_REQUEST'
Sat May 16 17:10:15 2020 192.168.157.1:62978 Delayed exit in 5 seconds
Sat May 16 17:10:15 2020 192.168.157.1:62978 SENT CONTROL [UNDEF]: 'AUTH_FAILED' (status=1)
Sat May 16 17:10:15 2020 192.168.157.1:62978 Connection reset, restarting [0]
Sat May 16 17:10:15 2020 192.168.157.1:62978 SIGUSR1[soft,connection-reset] received, client-instance restarting

**Comment by wheelybird** [comment]
Hi.  There's not much information in those logs - it just says that the user wasn't authenticated.  Take a look at your LDAP logs to see what the VPN container's trying to authenticate as.  

You can also try getting a shell in the VPN container (e.g. `docker exec -ti openvpn bash`) and using **pamtester** to test authenticating:  `yum install pamtester`.
Now kill the `nslcd` process (`kill 39` or whatever the process ID is) and run it in debug mode `nslcd -d &`.
Now run `pamtester -v openvpn [username] authenticate`.  That should give you some indication of why your user isn't authenticating.
