### ISSUE TITLE
Can you give me a config

### ISSUE THREAD

**Issue by AEGEGE** [wheelybird/openvpn-server-ldap-otp#39]
Hello,
      Can you give me an example of openvpn-ldap-ota docker startup? This example requires a password. The hub website gives me an example without a password. The findings I set myself cannot be used.Thanks！

**Comment by wheelybird** [comment]
I'm sorry, but I don't understand your request.  Which hub website?  The Docker Hub and git have the same README.
This container is designed to be used against an LDAP backend to authenticate users, and that will require the clients to provide login details.  If you don't want to use LDAP as the backend then you can elect to use certificates alone (https://github.com/wheelybird/openvpn-server-ldap-otp#using-a-client-certificate) but of course this isn't going to be properly secure:

```docker run \
           --name openvpn \
           --volume /path/on/host:/etc/openvpn \
           --detach=true \
           -p 1194:1194/udp \
           -e "OVPN_SERVER_CN=myserver.mycompany.com" \
           -e "USE_CLIENT_CERTIFICATE=true" \
           --cap-add=NET_ADMIN \
           wheelybird/openvpn-ldap-otp:v1.4```

**Comment by AEGEGE** [comment]
I want to use openldap as a storage backend
This is my configuration, please take a look
`docker run -d --restart=always --name openvpn-ldap-1 \
        --ulimit nofile=65536:65536 \
        -p 1194:1194/tcp \
        -e OVPN_PROTOCOL="tcp" \
        -e OVPN_NAT="false" \
        -e OVPN_SERVER_CN="openvpn.xxx.com" \
        -e OVPN_ROUTES="172.119.0.0 255.255.255.0" \
        -e OVPN_NETWORK="10.50.50.0 255.255.254.0" \
        -e LDAP_URI="ldap://172.119.0.233" \
        -e LDAP_BASE_DN="dc=xxx,dc=com" \
        -e LDAP_BIND_USER_DN="cn=admin,dc=xxx,dc=com" \
        -e LDAP_BIND_USER_PASS="xxxx" \
        --cap-add=NET_ADMIN \
        wheelybird/openvpn-ldap-otp:v1.4`

**Comment by AEGEGE** [comment]
docker run -d --restart=always --name openvpn-ldap-1 \
        --ulimit nofile=65536:65536 \
        -p 1194:1194/tcp \
        -e OVPN_PROTOCOL="tcp" \
        -e OVPN_NAT="false" \
        -e OVPN_SERVER_CN="openvpn.xxxx.com" \
        -e OVPN_ROUTES="172.119.0.0 255.255.255.0" \
        -e OVPN_NETWORK="10.50.50.0 255.255.254.0" \
        -e LDAP_URI="ldap://172.119.0.233" \
        -e LDAP_BASE_DN="dc=xxx,dc=com" \
        -e LDAP_BIND_USER_DN="cn=admin,dc=xxx,dc=com" \
        -e LDAP_BIND_USER_PASS="xxxxx" \
        -e LDAP_FILTER="ou=users,dc=xxx,dc=com" \
        --cap-add=NET_ADMIN \
        wheelybird/openvpn-ldap-otp:v1.4


I confirm that there is no error in the configuration of openldap, and the username and password are also set, but the wrong user is displayed during authentication

**Comment by wheelybird** [comment]
You haven't actually explained what problem you're having.  What's the actual error?

**Comment by AEGEGE** [comment]
Will prompt me that the account name and password are wrong

**Comment by wheelybird** [comment]
Do you mean the username/password for LDAP_BIND_USER_DN & LDAP_BIND_USER_PASS?  You're rather vague - it's hard to help you out without more information.  Can you post any relevant logs?

**Comment by AEGEGE** [comment]
Tue Jun  9 09:58:23 2020 36.110.47.57:6426 peer info: IV_GUI_VER="net.tunnelblick.tunnelblick_5440_3.8.2beta04__build_5440)"
AUTH-PAM: BACKGROUND: user 'test' failed to authenticate: Authentication service cannot retrieve authentication info
Tue Jun  9 09:58:32 2020 36.110.47.57:6426 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so/PLUGIN_AUTH_USER_PASS_VERIFY status=1
Tue Jun  9 09:58:32 2020 36.110.47.57:6426 PLUGIN_CALL: plugin function PLUGIN_AUTH_USER_PASS_VERIFY failed with status 1: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
Tue Jun  9 09:58:32 2020 36.110.47.57:6426 TLS Auth Error: Auth Username/Password verification failed for peer
Tue Jun  9 09:58:32 2020 36.110.47.57:6426 SIGTERM[soft,auth-control-exit] received, client-instance exiting
Tue Jun  9 09:58:33 2020 TCP connection established with [AF_INET]36.110.47.57:6427
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 TLS: Initial packet from [AF_INET]36.110.47.57:6427, sid=f9607e7e 0cdd201e
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_VER=2.4.8
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_PLAT=mac
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_PROTO=2
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_NCP=2
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_LZ4=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_LZ4v2=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_LZO=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_COMP_STUB=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_COMP_STUBv2=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_TCPNL=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 peer info: IV_GUI_VER="net.tunnelblick.tunnelblick_5440_3.8.2beta04__build_5440)"
AUTH-PAM: BACKGROUND: user 'test' failed to authenticate: Authentication service cannot retrieve authentication info
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so/PLUGIN_AUTH_USER_PASS_VERIFY status=1
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 PLUGIN_CALL: plugin function PLUGIN_AUTH_USER_PASS_VERIFY failed with status 1: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 TLS Auth Error: Auth Username/Password verification failed for peer
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA
Tue Jun  9 09:58:34 2020 36.110.47.57:6427 Peer Connection Initiated with [AF_INET]36.110.47.57:6427
Tue Jun  9 09:58:35 2020 36.110.47.57:6427 PUSH: Received control message: 'PUSH_REQUEST'
Tue Jun  9 09:58:35 2020 36.110.47.57:6427 Delayed exit in 5 seconds
Tue Jun  9 09:58:35 2020 36.110.47.57:6427 SENT CONTROL [UNDEF]: 'AUTH_FAILED' (status=1)
Tue Jun  9 09:58:35 2020 36.110.47.57:6427 Connection reset, restarting [0]
Tue Jun  9 09:58:35 2020 36.110.47.57:6427 SIGUSR1[soft,connection-reset] received, client-instance restarting

**Comment by wheelybird** [comment]
I see you're the same person that raised issue issue #34 .  I advised you to test using `pamtester`:

> You can also try getting a shell in the VPN container (e.g. docker exec -ti openvpn bash) and using pamtester to test authenticating: yum install pamtester.
Now kill the nslcd process (kill 39 or whatever the process ID is) and run it in debug mode nslcd -d &.
Now run pamtester -v openvpn [username] authenticate. That should give you some indication of why your user isn't authenticating.

This advice still holds.  The issue, as the logs clearly state, is that authentication is failing with the username and password you're trying.  As it's the LDAP server that you're using that's responsible for authenticating users, you have to check with the logs there to see why authentication is failing.
I'm not sure how you feel I can help you when I know nothing about your setup.

**Comment by AEGEGE** [comment]
Thanks for the help, this idea is very good, I will try to check it first.

**Comment by AEGEGE** [comment]
```
nslcd: DEBUG: ldap_set_option(LDAP_OPT_X_TLS_CACERTFILE,"/etc/pki/tls/certs/ca-bundle.crt")
nslcd: version 0.8.13 starting
nslcd: DEBUG: initgroups("nslcd",55) done
nslcd: DEBUG: setgid(55) done
nslcd: DEBUG: setuid(65) done
nslcd: accepting connections
nslcd: [8b4567] DEBUG: connection from pid=190 uid=0 gid=0
nslcd: DEBUG: accept() failed (ignored): Resource temporarily unavailable
nslcd: [8b4567] <authc="test"> DEBUG: nslcd_pam_authc("test","openvpn","***")
nslcd: [8b4567] <authc="test"> DEBUG: myldap_search(base="ou=users,dc=fthl,dc=com", filter="(&(objectClass=posixAccount)(uid=test))")
nslcd: [8b4567] <authc="test"> DEBUG: ldap_initialize(ldap://172.119.0.233)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_rebind_proc()
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_PROTOCOL_VERSION,3)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_DEREF,0)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_TIMELIMIT,0)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_TIMEOUT,0)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_NETWORK_TIMEOUT,0)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_REFERRALS,LDAP_OPT_ON)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_set_option(LDAP_OPT_RESTART,LDAP_OPT_ON)
nslcd: [8b4567] <authc="test"> DEBUG: ldap_simple_bind_s("cn=admin,dc=fthl,dc=com","***") (uri="ldap://172.119.0.233")
nslcd: [8b4567] <authc="test"> DEBUG: ldap_result(): end of results (0 total)
nslcd: [8b4567] <authc="test"> DEBUG: "test": user not found: No such object
```
I think I found the problem. The objectclass I used is inetorgperson, and the default is posixaccount

**Comment by wheelybird** [comment]
Your logs show that the filter being used here is `(objectClass=posixAccount)`, so unless you've defined that yourself via `LDAP_FILTER` then it looks like **nslcd** is setting that as the default (I'll update the documentation to reflect that).  Your LDAP users probably aren't posixAccounts - you need to check how they're set up and define LDAP_FILTER accordingly.

**Comment by AEGEGE** [comment]
The above problem has been solved perfectly, thank you for your help!
Now there is a problem, iptables will not be added after running, I have added --cap-add=NET_ADMIN when docker run, do you have any ideas to troubleshoot this problem?

**Comment by AEGEGE** [comment]
I found that only OVPN_NAT=true, then iptables will be added normally

**Comment by wheelybird** [comment]
Yes, the iptables is only required for IP masquerading (NAT).  Therefore if you set `OVPN_NAT` to `false` (as your examples above show) then the rule isn't added and you need to set up the appropriate routing on servers either side of the tunnel.  `OVPN_NAT` is set to `true` by default.
