### ISSUE TITLE
service fail2ban start error

### ISSUE THREAD

**Issue by zhyc9de** [wheelybird/openvpn-server-ldap-otp#40]
/opt/configuration/setup_fail2ban.sh: line 42: service: command not found

**Comment by wheelybird** [comment]
Sorry this took so long.  I've pushed the fix to master - you'll be able to use the `wheelybird/openvpn-ldap-otp:latest` Docker image to test it.

**Comment by vladivo** [comment]
@wheelybird first of all thank you so much for this great image! It works like a charm and is a quite essential part of my infrastructure :+1: 

The containers starts and fail2ban-server works properly, but I still can log in after more than defined amount of failed attempts. Only after I entered the running container and started fail2ban-server in foreground I could see what I assume is the problem. Here is the relevant log output:

> 2021-06-20 12:15:39,210 fail2ban.filter         [255]: INFO    [openvpn] Found 89.1.xxx.xxx - 2021-06-20 12:15:38
2021-06-20 12:15:39,504 fail2ban.actions        [255]: NOTICE  [openvpn] Ban 89.1.xxx.xxx
2021-06-20 12:15:39,791 fail2ban.utils          [255]: ERROR   7f2974643128 -- exec: ports="1194"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --add-rich-rule="rule family='ipv4' source address='89.1.xxx.xxx' port port='$p' protocol='udp' reject type='icmp-port-unreachable'"; done
2021-06-20 12:15:39,792 fail2ban.utils          [255]: ERROR   7f2974643128 -- stderr: 'Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory'
2021-06-20 12:15:39,793 fail2ban.utils          [255]: ERROR   7f2974643128 -- returned 36
2021-06-20 12:15:39,793 fail2ban.actions        [255]: ERROR   Failed to execute ban jail 'openvpn' action 'firewallcmd-rich-rules' info 'ActionInfo({'ip': '89.1.xxx.xxx', 'fid': <function <lambda> at 0x7f2975ddac80>, 'family': 'inet4', 'raw-ticket': <function <lambda> at 0x7f2975ddc2a8>})': Error banning 89.1.xxx.xxx

I hoped that this is something trivial and tried to google the solution, but without luck. This is already a too low-level for me.

**Comment by francesco74** [comment]
Use this content for file "files/bin/entrypoint" and then rebuild the image

`#!/bin/bash

if [ "$DEBUG" == "true" ]; then
  set -x
fi
set -e

CONFIGFILES="/opt/configuration"

source "$CONFIGFILES/set_defaults.sh"
source "$CONFIGFILES/setup_networking.sh"
source "$CONFIGFILES/setup_pki.sh"

if [ "${USE_CLIENT_CERTIFICATE}" != "true" ] ; then
 source "$CONFIGFILES/setup_ldap.sh"
 source "$CONFIGFILES/setup_otp.sh"
fi

source "$CONFIGFILES/create_server_config.sh"

echo
echo "***************"
echo " Client config "
echo "***************"
echo
/usr/local/bin/show-client-config

echo
echo "***************"
echo "Running NSCLD"
echo "***************"
echo
nslcd

if [ "${FAIL2BAN_ENABLED}" == "true" ] ; then

  echo 
  echo "****************"
  echo "Starting dbus"
  echo "****************"
  dbus-uuidgen > /var/lib/dbus/machine-id
  mkdir -p /var/run/dbus
  dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address

  echo 
  echo "*********************"
  echo "Starting firewall"
  echo "*********************"
  echo
  /usr/bin/python2 -Es /usr/sbin/firewalld
  sleep 5
  firewall-cmd --zone=public --add-port=1194/$OVPN_PROTOCOL

  if [ "${OVPN_NAT}" == "true" ] ; then
    firewall-cmd --add-masquerade
  fi

  source "$CONFIGFILES/setup_fail2ban.sh"
fi

echo
echo "***************"
echo "Running OpenVPN"
echo "***************"
echo
openvpn --config $OPENVPN_DIR/server.conf `

This should work...I'm already testing but should work.
If there is some error or a better way to do things let me know...

**Comment by wheelybird** [comment]
Cheers.  I haven't had a chance to look properly, but I was hoping there was a way to do this without running dbus.  I'm pretty sure dbus isn't supposed to be a dependency for fail2ban.

**Comment by francesco74** [comment]
...maybe the firewalld?

**Comment by vladivo** [comment]
@francesco74, just tested your solution and it works. Thank you.

I also noticed the dbus error when running `docker build`. It appears during first `yum install` on line 5 of the Dockerfile:

> Running transaction
  Updating   : glibc-2.17-324.el7_9.x86_64                                 1/22 
  Updating   : glibc-common-2.17-324.el7_9.x86_64                          2/22 
  Updating   : 1:openssl-libs-1.0.2k-21.el7_9.x86_64                       3/22 
  Installing : libnfnetlink-1.0.1-4.el7.x86_64                             4/22 
  Installing : libmnl-1.0.3-7.el7.x86_64                                   5/22 
  Installing : libnetfilter_conntrack-1.0.6-1.el7_3.x86_64                 6/22 
  Installing : 1:make-3.82-24.el7.x86_64                                   7/22 
  Updating   : systemd-libs-219-78.el7_9.3.x86_64                          8/22 
  Updating   : systemd-219-78.el7_9.3.x86_64                               9/22 
Failed to get D-Bus connection: Operation not permitted
  Installing : nscd-2.17-324.el7_9.x86_64                                 10/22 
  Installing : systemd-sysv-219-78.el7_9.3.x86_64                         11/22 
  Installing : nss-pam-ldapd-0.8.13-25.el7.x86_64                         12/22 
  Installing : net-tools-2.0-0.25.20131004git.el7.x86_64                  13/22 
  Installing : 1:openssl-1.0.2k-21.el7_9.x86_64                           14/22 
  Installing : iptables-1.4.21-35.el7.x86_64                              15/22 
  Installing : wget-1.14-18.el7_6.1.x86_64                                16/22 
install-info: No such file or directory for /usr/share/info/wget.info.gz
  Installing : epel-release-7-11.noarch                                   17/22 
  Cleanup    : systemd-219-78.el7.x86_64                                  18/22 
  Cleanup    : systemd-libs-219-78.el7.x86_64                             19/22

**Comment by vladivo** [comment]
@wheelybird just tested your latest release (Christmas tunnels). Fail2ban works perfectly and this issue can be closed now. Thank you so much!
