### ISSUE TITLE
How to regenerate a valid 2FA code

### ISSUE THREAD

**Issue by laoqin2601** [wheelybird/openvpn-server-ldap-otp#48]
add-otp-user jim (i did not save the 2FA code at first time)

add-otp-user jim  (i save the code at this time, but it AUTH_FAILED)

**Comment by wheelybird** [comment]
The OTP information is updated each time you run add-otp-user, so I suspect that the authentication failure is happening due to another reason.

**Comment by laoqin2601** [comment]
thanks! nice job.
