### ISSUE TITLE
Options error: bad comp option: migrate in v1.7

### ISSUE THREAD

**Issue by anipad** [wheelybird/openvpn-server-ldap-otp#65]
Thank you for the latest release bump. However, after trying to upgrade to v1.7 I receive the following error log and container restarts.

```
2023-05-03` 21:29:17 - Starting NSCLD... (ignore any NSS_LDAP module warnings)
nslcd: Warning: NSS_LDAP module not loaded: libnss_ldap.so.2: cannot open shared object file: No such file or directory
2023-05-03 21:29:18 - Running OpenVPN...
Options error: bad comp option: migrate
Use --help for more information.
```

Same result with and without `- OVPN_ENABLE_COMPRESSION=false` in my docker compose file. So far i have to stay on v.1.6, which works like a charm.
Thanks for any help.

**Comment by wheelybird** [comment]
Hi.  Thanks for the report.  Can you tell me which architecture you're running on (is it an ARM host?)

**Comment by wheelybird** [comment]
I've just checked - the ARM build is using an older version of OpenVPN.  I'll try to fix that.

**Comment by anipad** [comment]
Yes, i am indeed running an ARM build. Thanks!

**Comment by wheelybird** [comment]
I've just pushed v1.8 which fixes this issue.  It's working on my Raspberry Pi now.

**Comment by anipad** [comment]
v1.8 ARM works as intended. Thank you
