### ISSUE TITLE
Can't start the container : exited (139)

### ISSUE THREAD

**Issue by Crivaledaz** [wheelybird/openvpn-server-ldap-otp#7]
Hi, 

I never used Docker before, so it is certainly a noob problem.

I can't start the container. After 'docker run' finished, the container is not running and with 'docker ps -a' I get the following : `COMMAND : /usr/local/bin/entrypoint"     STATUS : Exited (139) 4 seconds ago`

When I try to start the container with 'docker start openvpn', it just prompts "openvpn" on stdout and I get the same output from 'docker ps -a'

What I am doing wrong ?

Thank you in advance

Docker 18.06 on ArchLinux Kernel 4.18.3

**Comment by wheelybird** [comment]
It's hard to say.  The example to run the container in the README works.  What's the command that you're running to start the container?

**Comment by Crivaledaz** [comment]
First, I tried with OTP enabled : `docker run --name openvpn --volume /opt/docker:/etc/openvpn --detach=true -p 1194:1194/udp -e "OVPN_SERVER_CN=vpn.ldap.test" -e "LDAP_URI=ldap://192.168.42.100:389" -e "LDAP_BASE_DN=ou=VPN,dc=ldap,dc=test" -e "ENABLE_OTP=true" --cap-add=NET_ADMIN wheelybird/openvpn-ldap-otp`

Also I tried directly with the command line from the Readme : `docker run --name openvpn --volume /opt/docker:/etc/openvpn --detach=true -p 1194:1194/udp -e "OVPN_SERVER_CN=vpn.ldap.test" -e "LDAP_URI=ldap://192.168.42.100" -e "LDAP_BASE_DN=ou=VPN,dc=ldap,dc=test" --cap-add=NET_ADMIN wheelybird/openvpn-ldap-otp` 

I have the same problem in both case. I  found nothing about this Docker error on internet :/

Regards

**Comment by wheelybird** [comment]
What do you get from `docker logs openvpn`?

**Comment by Crivaledaz** [comment]
I got nothing with `docker logs openvpn`
I have done again the 'docker run' in a clean configuration (I deleted image and container). I share with you a screenshot of my terminal, to clarify : 

![docker_error](https://user-images.githubusercontent.com/30313991/44470730-c17f9000-a62a-11e8-932d-9e27e8ef1259.png)

Thank you for your help

**Comment by wheelybird** [comment]
The command you're using looks fine; it should work.  I suspect there's something odd about your Docker setup.  Are you using Linux on a x86 CPU?  i.e. not a Rasperry PI.

Try replacing `--detach` with `-ti` to get an interactive container instead.

**Comment by Crivaledaz** [comment]
Hi,

I have tried the container on Fedora and it works perfectly. I think Arch Linux is not the best choice to begin with Docker.

Thank you for your help

**Comment by RichGuk** [comment]
Just came across this issue too (also on Arch). Think its related to: https://github.com/CentOS/sig-cloud-instance-images/issues/62; https://github.com/pypa/manylinux/issues/254; https://github.com/moby/moby/issues/28705#issuecomment-262226229. 

Might be worth upgrading to centos7? There is this fork: https://github.com/benohara/openvpn-server-ldap-otp/tree/centos7

**Comment by wheelybird** [comment]
Hi.  Is this on Arch for x86 or arm?

**Comment by RichGuk** [comment]
Mine is for x86. I'm assuming the newer kernel doesn't have the required vsyscall that centos6 is requiring.

**Comment by wheelybird** [comment]
Rightho.  I've just created a new image (wheelybird/openvpn-server-ldap-otp:centos7) using benohara's fork.  It's available now, but I haven't tested it yet.  If you want to give it a spin, go for it.
