### ISSUE TITLE
docker image wheelybird/openvpn-ldap-otp:v1.8 log error

### ISSUE THREAD

**Issue by zhao-jing-hui** [wheelybird/openvpn-server-ldap-otp#73]
![image](https://github.com/wheelybird/openvpn-server-ldap-otp/assets/71484934/2523221f-bbe2-4141-b98d-bd9b637d6c3d)
error logs
-----

Host: nix | Linux | 

Easy-RSA error:

Unknown cert type 'server'

Host: nix | Linux | 

Easy-RSA error:

Failed to sign '116.63.55.58' - See error messages above for details.

In addition, when docker -v persistent deployment is used, modifying the server.conf of the host to add a route to restart the docker container does not take effect in the container

**Comment by fency12** [comment]
+1.  相同的镜像在docker Version: 26.1.4 下启动正常。在 Version:18.03.1-ce 运行报这个错
