### ISSUE TITLE
Bug with add-otp-user script in batch mode

### ISSUE THREAD

**Issue by trombonax** [wheelybird/openvpn-server-ldap-otp#77]
Hello

`google-authenticator` utility which used for 2fa codes generation now is interactive by default, so use `/usr/local/bin/add-otp-user` script in a batch mode isn't possible for releases later than 1.6.
Please, add `--no-confirm` flag for `google-authenticator` utility in `/usr/local/bin/add-otp-user` script.

Thank you.

**Comment by wheelybird** [comment]
Cheers!  I'm just pushing that fix.  You will need to `docker pull openvpn-ldap-otp:v.18` to pick up the change.

**Comment by trombonax** [comment]
Thank you

**Comment by trombonax** [comment]
Hello,
just now checked `/usr/local/bin/add-otp-user` script in a batch mode, works great.
Thank you again.
