### ISSUE TITLE
centos7无法使用

### ISSUE THREAD

**Issue by zhao-jing-hui** [wheelybird/openvpn-server-ldap-otp#84]
我和我的伙伴同样的配置 用ubuntu就可以正常工作，用centos7试了半天都不行

**Comment by wheelybird** [comment]
该镜像已经基于 Ubuntu 很长时间了。 Centos 项目本身已经停止，所以我无法支持旧的基于 Centos 的镜像。

(The image has been based on Ubuntu for a long time now.  The Centos project itself has been discontinued, so I can't support the older Centos based images.)
